version: '3.8'
services: 
    web:
        image: nginx:1.13.0-alpine
        container_name: wrk-nginx
        restart: always
        ports: 
        - "8891:80"
        volumes: 
        - ./nginx/scr:/var/www/html/